<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5yy3xTy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5yy3xTy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5yy3xTy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5yy3xTy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5yy3xTy\App_KernelDevDebugContainer([
    'container.build_hash' => '5yy3xTy',
    'container.build_id' => '370d858a',
    'container.build_time' => 1681585521,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5yy3xTy');
