<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXgNLZUc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXgNLZUc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXgNLZUc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXgNLZUc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXgNLZUc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XgNLZUc',
    'container.build_id' => '0805339b',
    'container.build_time' => 1681653978,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXgNLZUc');
