<?php
namespace tests;

use App\Helpers\ArticleReadingTime;
use PHPUnit\Framework\TestCase;

class ArticleTest extends TestCase
{
    public function testGetReadingTime()
    {
        $articleReadingTime = new ArticleReadingTime();
        $articleText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at purus augue.";
        $readingTime = $articleReadingTime->getReadingTime($articleText);
        $this->assertEquals(1, $readingTime);
    }

    public function testGetReadingTimeWithLongerArticle()
    {
        $articleReadingTime = new ArticleReadingTime();
        $articleText = "
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et justo neque. Aliquam erat volutpat. Morbi fringilla leo eget odio fringilla, sed feugiat leo efficitur. Vestibulum ut massa accumsan, volutpat ligula eget, maximus ligula. Maecenas blandit molestie metus, quis fringilla odio pharetra id. Phasellus mattis, nisi vel aliquet aliquet, sapien lacus tincidunt risus, sed ullamcorper nisi tortor sit amet metus. Sed ac laoreet lectus.
        In neque risus, suscipit eget mattis at, volutpat at urna. Morbi varius leo quis enim finibus congue. Curabitur bibendum porta lectus quis blandit. Praesent sed nisl eu mi egestas aliquam. Quisque finibus commodo ullamcorper. Praesent mattis dapibus ipsum in imperdiet. Morbi tincidunt orci vel luctus sodales. Nunc nec quam fringilla, consectetur orci quis, facilisis magna.
        Nulla facilisi. Fusce eu ligula sed libero luctus congue. Integer interdum quam neque, in ullamcorper odio imperdiet eget. Maecenas eu eros sit amet nunc sagittis tempor elementum eu nibh. Donec ut pellentesque magna. Nulla in iaculis mi. Curabitur velit purus, pretium non vehicula in, consequat in quam.
        Phasellus id diam nec nulla accumsan rhoncus. Nulla id eros in sapien pretium dictum. Nam eleifend mollis faucibus. Nunc quis mauris augue. Sed quis facilisis justo. Nullam egestas pharetra nulla, quis rutrum odio gravida ut. Suspendisse sollicitudin augue et lorem convallis iaculis. Duis quis purus id tortor rhoncus pulvinar a id mi. Suspendisse tellus dui, ornare id eleifend eget, facilisis vel massa. Mauris tortor odio, ultricies fermentum mauris non, aliquet iaculis lectus. Praesent a tellus nibh.
        Suspendisse rhoncus tincidunt mauris, non congue turpis vulputate vitae. Phasellus mollis lacinia est ac imperdiet. Vestibulum dolor nulla, hendrerit et nibh vitae, elementum accumsan lorem. In vehicula sapien ac imperdiet faucibus. Phasellus in feugiat lacus. Vivamus sed lobortis sapien. Sed sit amet dui leo. In vehicula nisi metus, eu ultrices nunc euismod sed. Quisque maximus a orci a.";
        $readingTime = $articleReadingTime->getReadingTime($articleText);
        $this->assertEquals(2, $readingTime);
    }

    public function testGetReadingTimeWithEmptyArticle()
    {
        $articleReadingTime = new ArticleReadingTime();
        $articleText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at purus augue. Cras blandit velit sit amet semper varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent aliquam lectus sit amet ligula accumsan pellentesque. Vivamus pellentesque dapibus condimentum. Aliquam ac tempor sem, at sollicitudin ipsum. Maecenas vestibulum nisl a elit congue, in faucibus felis sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque id urna vitae ante efficitur facilisis in nec nunc. Sed posuere tortor eget facilisis laoreet. Aliquam viverra eget metus in interdum. Nam rhoncus, felis laoreet feugiat vestibulum, leo nisl euismod justo, ac facilisis nisl quam eu sapien. Fusce sagittis augue eu tellus dignissim convallis. Nam in nisl semper, dignissim ipsum ut, pretium neque. Ut fringilla consectetur orci, ac varius lorem lacinia ac.
        Vivamus iaculis mattis tellus non aliquam. Nam sit amet fermentum augue. Curabitur luctus orci ac tempor porttitor. Cras elementum nunc sit amet varius tincidunt. Ut et ipsum odio. Morbi ut rutrum libero. Aliquam cursus sem in leo semper, id vehicula lorem tincidunt. Donec nec nibh efficitur, gravida sapien non, faucibus ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam in faucibus lorem, vel gravida arcu. Aliquam in purus in libero eleifend dapibus in vel ante.
        In pharetra congue velit. Donec ac ligula at turpis tincidunt volutpat. Sed maximus tortor feugiat mattis scelerisque. Ut feugiat aliquam bibendum. Integer eleifend imperdiet nisl posuere consectetur. Donec dapibus erat eget dignissim egestas. Mauris convallis sapien quis arcu sagittis tincidunt. Nullam at diam erat. Donec magna leo, ultrices et pulvinar blandit, pulvinar ut nunc. Sed a velit ante. Vivamus dapibus fringilla risus, quis posuere lorem euismod vitae. Donec posuere non quam et auctor.
        Integer ultrices convallis massa, a tincidunt erat viverra at. Aenean metus sem, imperdiet et euismod ac, iaculis et mauris. Nam non magna dapibus, commodo orci nec, ullamcorper nunc. Praesent pretium, nisi ac suscipit placerat, risus diam fermentum nisl, ac suscipit urna erat non ligula. Etiam dapibus elit eget bibendum dignissim. Sed laoreet viverra lorem, non imperdiet diam bibendum eu. Sed eget vestibulum lacus. In quis nunc felis. Aliquam sit amet neque ac tortor pulvinar egestas vitae sit amet nulla. Phasellus suscipit pretium nisl eget consectetur. In commodo ac justo vel pulvinar.
        Donec in vulputate est, ac imperdiet nulla. Mauris ut vestibulum nisi, a malesuada nulla. Sed lacus lorem, pulvinar eget tincidunt vel, tincidunt et arcu. Phasellus ac sapien dui. Curabitur mattis fermentum nisi sit amet cursus. Nunc ut odio eget augue imperdiet venenatis sit amet vitae dui. Donec aliquam metus nec sapien ullamcorper blandit at sed mauris. Duis non est in lorem dictum mollis. Cras ex purus, venenatis id lobortis at, condimentum eu purus. Sed dapibus ullamcorper metus non venenatis. Proin rhoncus mauris aliquet, rhoncus libero eget, pulvinar lorem. Nulla elementum erat at ultricies dictum. Pellentesque eleifend, arcu nec blandit aliquet, risus odio tincidunt felis, vitae ultricies est ipsum eu mi. Etiam maximus lectus ex, at malesuada sapien fermentum sed.
        Nullam eget feugiat nibh. Fusce rutrum bibendum mi vitae consequat. Donec congue fringilla ante. Nulla sit amet eros rutrum, luctus augue eu, porta orci. Vivamus vitae lectus sagittis, efficitur nibh sit amet, volutpat justo. Nullam tincidunt elit at sem pellentesque placerat nec id eros. Donec porta volutpat dui ut mollis. Sed tincidunt convallis urna, tempor tincidunt metus gravida consequat. Aenean aliquet posuere nisi. Mauris sollicitudin ut orci et vehicula. Proin metus dui, sodales ac fermentum sit amet, faucibus non ligula. Integer quam lacus, tempus vel tempus vitae, tincidunt id sapien. Nulla gravida, neque et fringilla laoreet, erat velit consectetur enim, in vulputate metus nibh vitae sapien. Ut congue blandit dictum.
        Nulla urna lacus, rhoncus quis pharetra auctor, placerat ut nisl. Suspendisse vitae magna dapibus, viverra nulla sed, interdum justo. Maecenas bibendum ultrices mi at mollis. Fusce porta pretium arcu, sit amet aliquet felis lobortis nec. Curabitur sed neque dolor. Proin est arcu, luctus eu pellentesque non, pulvinar ac mauris. Nulla facilisi. Quisque blandit massa ut purus tristique egestas. Nunc ullamcorper tincidunt nibh, vitae aliquet tellus vehicula et. Donec sagittis libero in nisl varius, rutrum tincidunt purus sodales.
        Duis cursus, massa non ultricies accumsan, lacus mauris faucibus nisl, sit amet iaculis risus augue vitae ipsum. Nunc porta nunc lectus, sed pulvinar erat varius eu. In rutrum velit ex, nec malesuada enim sollicitudin vitae. Proin nec nibh vehicula tortor ultrices tempus. Integer in libero quis erat congue tempor. Donec id urna diam. Proin libero quam, porta ac lacinia eget, posuere a erat. 
        Phasellus id enim orci. Duis eget condimentum ex, a sodales eros. Proin vehicula eleifend nunc, et lacinia enim tincidunt eu. Pellentesque vestibulum massa quis condimentum tristique. Quisque vel mauris velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam tellus turpis, placerat eget justo sit amet, laoreet auctor sem. Donec fermentum lorem lacus, et sollicitudin tellus laoreet et. Quisque efficitur tincidunt nisl id rhoncus. Suspendisse facilisis, purus in posuere eleifend, eros nibh hendrerit libero, vitae luctus ante quam id urna. Donec condimentum venenatis elit, tristique mattis mi mattis nec. Pellentesque congue iaculis risus, at semper odio elementum in. Duis auctor erat enim, quis venenatis arcu fringilla a. Nullam pretium urna varius urna ullamcorper, eget suscipit justo ornare. Quisque cursus vulputate augue non finibus.
        In blandit interdum eleifend. Duis dignissim nulla vel pulvinar ornare. Integer sollicitudin iaculis urna, eu eleifend lacus. Vestibulum sed dapibus urna, pellentesque aliquet tortor. Suspendisse luctus, sapien eleifend suscipit sollicitudin, dui lacus tempus elit, sed tincidunt metus tortor ac ipsum. Maecenas pharetra ac leo condimentum ullamcorper. Pellentesque tincidunt tempor lectus non porta. Ut at semper risus, nec fermentum lorem. Suspendisse id odio eget quam malesuada fermentum at eget magna
        Donec id mi finibus, consectetur turpis a, dictum nunc. Fusce non elementum mi. Mauris faucibus, metus at mollis laoreet, ante leo vestibulum sem, id semper neque ligula eu dui. Nunc ut orci metus. Morbi a diam venenatis, pretium sem eget, malesuada lorem. Ut mauris risus, sodales eu posuere eu, semper et velit. Etiam mauris.";
        $readingTime = $articleReadingTime->getReadingTime($articleText);
        $this->assertEquals(5, $readingTime);
    }
}