<?php

namespace ContainerXgNLZUc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZVxSbHGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zVxSbHG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zVxSbHG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ArticalFormHelper' => ['privates', 'App\\Helpers\\ArticalFormHelper', 'getArticalFormHelperService', true],
            'article' => ['privates', '.errored..service_locator.zVxSbHG.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.zVxSbHG": it references class "App\\Entity\\Article" but no such service exists.'],
            'cacheHelper' => ['privates', 'App\\Helpers\\CacheHelper', 'getCacheHelperService', true],
        ], [
            'ArticalFormHelper' => 'App\\Helpers\\ArticalFormHelper',
            'article' => 'App\\Entity\\Article',
            'cacheHelper' => 'App\\Helpers\\CacheHelper',
        ]);
    }
}
