<?php

namespace ContainerVZj8PZ0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCacheHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Helpers\CacheHelper' shared autowired service.
     *
     * @return \App\Helpers\CacheHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Helpers/CacheHelper.php';

        return $container->privates['App\\Helpers\\CacheHelper'] = new \App\Helpers\CacheHelper();
    }
}
