<?php

namespace Container5yy3xTy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticalFormHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Helpers\ArticalFormHelper' shared autowired service.
     *
     * @return \App\Helpers\ArticalFormHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Helpers/ArticalFormHelper.php';

        $a = ($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService'));

        if (isset($container->privates['App\\Helpers\\ArticalFormHelper'])) {
            return $container->privates['App\\Helpers\\ArticalFormHelper'];
        }

        return $container->privates['App\\Helpers\\ArticalFormHelper'] = new \App\Helpers\ArticalFormHelper(($container->services['doctrine'] ?? $container->getDoctrineService()), $a);
    }
}
