<?php

namespace Container4pRVzYt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fn4PKlQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fn4PKlQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fn4PKlQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'cacheHelper' => ['privates', 'App\\Helpers\\CacheHelper', 'getCacheHelperService', true],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'cacheHelper' => 'App\\Helpers\\CacheHelper',
        ]);
    }
}
